export default [
  {'title': 'Дозапрос по изменению комиссии',
    'code': 'review_change_cr_aq',
    'role': 'underwriter',
    'stage': 'Согласование правок'
  },
  {'title': 'Изменение правок',
    'code': 'changes',
    'role': 'agent',
    'stage': 'Согласование правок'},
  {'title': 'Предложение банка с отлагательными условиями!',
    'code': 'accept_offer_add',
    'role': 'agent',
    'stage': 'Согласование правок'},
  {'title': 'Анализ выписки СД',
    'code': 'analys_sd',
    'role': 'underwriter',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Дозапрос по рассмотрению заявки на СД',
    'code': 'review_on_sd_underwriter_aq',
    'role': 'underwriter',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Рассмотрение заявки на СД',
    'code': 'review_on_sd',
    'role': 'colleg_org',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Соответствия условий СК и КК',
    'code': 'correspondence_sk_and_kk',
    'role': 'underwriter',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Анализ выписки КК',
    'code': 'analys_kk',
    'role': 'underwriter',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Рассмотрение заявки на СК',
    'code': 'review_on_sk',
    'role': 'insurance_company',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Дозапрос по рассмотрению заявки на КК',
    'code': 'review_on_kk_underwriter_aq',
    'role': 'underwriter',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Рассмотрение заявки на КК',
    'code': 'review_on_kk',
    'role': 'colleg_org',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Индивидуальная БГ?',
    'code': 'is_individual_bg',
    'role': 'system',
    'stage': 'Коллегиальное принятие решения'},
  {'title': 'Дозапрос "Формирование комплектности документов для выдачи и счета на оплату"',
    'code': 'issuance_docs_set_forming_manager_aq',
    'role': 'underwriter',
    'stage': 'Оформление заявки'},
  {'title': 'Дозапрос "Проверка анкеты"',
    'code': 'check_survey_manager_aq',
    'role': 'underwriter',
    'stage': 'Верификация'},
  {'title': 'Изменение комиссии',
    'code': 'change_cr',
    'role': 'curator',
    'stage': 'Согласование правок'},
  {'title': 'Дозапрос "Оплата и документы"',
    'code': 'check_payment_and_sign_by_issuance_agent_aq',
    'role': 'agent',
    'stage': 'Оплата и документы'},
  {'title': 'Дозапрос "Проверка оплаты в АБС и ЭЦП принципала"',
    'code': 'check_payment_and_sign_by_issuance_manager_aq',
    'role': 'manager',
    'stage': 'Оплата и документы'},
  {'title': 'Дозапрос "Контроль оплаты КВ в АБС"',
    'code': 'control_payment_abs_agent_aq',
    'role': 'agent',
    'stage': 'Оплата и документы'},
  {'title': 'Дозапрос "Оплата и документы"',
    'code': 'accept_check_list_agent_aq',
    'role': 'agent',
    'stage': 'Оплата и документы'},
  {'title': 'Дозапрос "Акцепт чек-листа досье БГ"',
    'code': 'accept_check_list_manager_aq',
    'role': 'manager',
    'stage': 'Оплата и документы'},
  {'title': 'Дозапрос "Формирование комплектности документов для выдачи и счета на оплату"',
    'code': 'issuance_docs_set_forming_agent_aq',
    'role': 'agent',
    'stage': 'Оплата и документы'},
  {'title': 'Дозапрос "Согласование правок"',
    'code': 'atypical_bg_project_forming_agent_aq',
    'role': 'agent',
    'stage': 'Согласование правок'},
  {'title': 'Дозапрос "Подготовка нетипового проекта БГ"',
    'code': 'atypical_bg_project_forming_manager_aq',
    'role': 'manager',
    'stage': 'Согласование правок'},
  {'title': 'Дозапрос "Согласование правок"',
    'code': 'bg_project_changes_approval_agent_aq',
    'role': 'agent',
    'stage': 'Согласование правок'},
  {'title': 'Дозапрос "Согласование правок в проекте БГ"',
    'code': 'bg_project_changes_approval_manager_aq',
    'role': 'manager',
    'stage': 'Согласование правок'},
  {'title': 'Дозапрос "Согласование проекта БГ"',
    'code': 'bg_project_approval_agent_aq',
    'role': 'agent',
    'stage': 'Согласование правок'},
  {'title': 'Дозапрос "Подготовка заключений"',
    'code': 'domc_underwriting_agent_aq',
    'role': 'agent',
    'stage': 'Подготовка заключений'},
  {'title': 'Дозапрос "Проверка заключения УРДО и комплектности"',
    'code': 'domc_underwriting_manager_aq',
    'role': 'manager',
    'stage': 'Подготовка заключений'},
  {'title': 'Дозапрос "Подготовка заключений"',
    'code': 'lawyers_dep_conclusion_forming_agent_aq',
    'role': 'agent',
    'stage': 'Подготовка заключений'},
  {'title': 'Дозапрос "Подготовка заключения ПУ"',
    'code': 'lawyers_dep_conclusion_forming_manager_aq',
    'role': 'manager',
    'stage': 'Подготовка заключений'},
  {'title': 'Дозапрос "Подготовка заключений"',
    'code': 'security_dep_conclusion_forming_agent_aq',
    'role': 'agent',
    'stage': 'Подготовка заключений'},
  {'title': 'Дозапрос "Подготовка заключения СБ"',
    'code': 'security_dep_conclusion_forming_manager_aq',
    'role': 'manager',
    'stage': 'Подготовка заключений'},
  {'title': 'Дозапрос "Проверка анкеты"',
    'code': 'check_survey_agent_aq',
    'role': 'agent',
    'stage': 'Верификация'},
  {'title': 'Дозапрос "Проверка комплектности"',
    'code': 'completeness_agent_aq',
    'role': 'agent',
    'stage': 'Верификация'},
  {'title': 'Дозапрос "Подготовка заключений"',
    'code': 'domc_forming_agent_aq',
    'role': 'agent',
    'stage': 'Подготовка заключений'},
  {'title': 'Дозапрос "Подготовка проекта заключения УРДО"',
    'code': 'domc_forming_manager_aq',
    'role': 'manager',
    'stage': 'Подготовка заключений'},
  {'title': 'Проверка наличия ЭЦП заключения УРДО',
    'code': 'check_sign_domc_2',
    'role': 'system',
    'stage': 'Согласование правок'},
  {'title': 'Проверка наличия итогов конкурса',
    'code': 'check_tender_3',
    'role': 'system',
    'stage': 'Согласование правок'},
  {'title': 'Подготовка и выдача БГ',
    'code': 'issuance',
    'role': 'final_documents',
    'stage': 'Предоставление БГ'},
  {'title': 'Проверка оплаты в АБС и ЭЦП принципала',
    'code': 'check_payment_and_sign_by_issuance',
    'role': 'final_documents',
    'stage': 'Оплата и документы'},
  {'title': 'Контроль оплаты КВ в АБС',
    'code': 'control_payment_abs',
    'role': 'manager',
    'stage': 'Оплата и документы'},
  {'title': 'Контроль оплаты',
    'code': 'control_payment',
    'role': 'agent',
    'stage': 'Оплата и документы'},
  {'title': 'Контроль подписания',
    'code': 'control_signing',
    'role': 'agent',
    'stage': 'Оплата и документы'},
  {'title': 'Акцепт чек-листа досье БГ',
    'code': 'accept_check_list',
    'role': 'final_documents',
    'stage': 'Оплата и документы'},
  {'title': 'Формирование комплектности документов для выдачи и счета на оплату',
    'code': 'issuance_docs_set_forming',
    'role': 'manager',
    'stage': 'Оплата и документы'},
  {'title': 'Проверка наличия ЭЦП заключения УРДО',
    'code': 'check_sign_domc',
    'role': 'system',
    'stage': 'Согласование правок'},
  {'title': 'Ожидание итогов конкурса',
    'code': 'waiting_tender_win',
    'role': 'agent',
    'stage': 'Согласование правок'},
  {'title': 'Подготовка нетипового проекта БГ',
    'code': 'atypical_bg_project_forming',
    'role': 'escort',
    'stage': 'Согласование правок'},
  {'title': 'Согласование правок в проекте БГ',
    'code': 'bg_project_changes_approval',
    'role': 'legal_departament',
    'stage': 'Согласование правок'},
  {'title': 'Проверка наличия итогов конкурса',
    'code': 'check_tender_2',
    'role': 'system',
    'stage': 'Согласование правок'},
  {'title': 'Согласование проекта БГ',
    'code': 'bg_project_approval',
    'role': 'manager',
    'stage': 'Согласование правок'},
  {'title': 'Предложение банка!',
    'code': 'accept_offer',
    'role': 'agent',
    'stage': 'Согласование правок'},
  {'title': 'Предложение с отлагательными условиями',
    'code': 'suspended_offer',
    'role': 'underwriter',
    'stage': 'Согласование правок'},
  {'title': 'Проверка наличия итогов конкурса',
    'code': 'check_tender_winner',
    'role': 'system',
    'stage': 'Согласование правок'},
  {'title': 'Формирование предложения, проекта БГ, счёта на оплату и ЭЦП УРДО',
    'code': 'forming_offer',
    'role': 'underwriter',
    'stage': 'Согласование правок'},
  {'title': 'Проверка заключения УРДО и комплектности',
    'code': 'domc_underwriting',
    'role': 'underwriter',
    'stage': 'Подготовка заключений'},
  {'title': 'Подготовка заключения ПУ',
    'code': 'lawyers_dep_conclusion_forming',
    'role': 'legal_departament',
    'stage': 'Подготовка заключений'},
  {'title': 'Подготовка заключения СБ',
    'code': 'security_dep_conclusion_forming',
    'role': 'security_service',
    'stage': 'Подготовка заключений'},
  {'title': 'Проверка анкеты',
    'is_starting': true,
    'code': 'check_survey',
    'role': 'manager',
    'stage': 'Верификация'},
  {'title': 'Проверка комплектности',
    'code': 'completeness',
    'has_aq': true,
    'role': 'manager',
    'stage': 'Верификация'},
  {'title': 'Подготовка проекта заключения УРДО',
    'code': 'domc_forming',
    'role': 'underwriter',
    'stage': 'Подготовка заключений'}
]
